//! Copied from ark's `ark-language-server/src/main.rs` — the file, not the
//! idea: same stack (`lsp-server` + `lsp-types`, no async runtime), same
//! crossbeam `select!` event loop over the connection and a threadpool, same
//! `MainLoopTask` shapes, same stale-diagnostics clearing via
//! `files_with_errors`. Deviations, each forced and declared:
//!
//! - **Projects are directories.** Ark walks for `ark-project.json` naming a
//!   `main` file; yel's package *is* a directory (`plans/modules.md` §4), so
//!   `find_projects` looks for `yel-project.json` first and otherwise treats
//!   any workspace directory containing `.yel` files as a project.
//! - **Compilation is `yelc_hir::check_package`** (ark: `check_program`) with
//!   the open buffers overlaid — ark recompiles from disk on save; overlays
//!   let diagnostics track unsaved edits.
//! - **Nothing non-`Send` crosses threads.** Ark ships `Arc<ast::File>`
//!   between workers; yel's trees are cheap to reparse, so workers parse from
//!   the content they are handed and only paths, strings and diagnostics
//!   travel.

use crossbeam::channel::{Receiver, Sender};
use crossbeam::select;
use lsp_server::{Connection, Message, Notification};
use lsp_types::notification::{self, Notification as _};
use lsp_types::request::{self, Request};
use lsp_types::{
    ClientCapabilities, Diagnostic, DiagnosticSeverity, DidChangeTextDocumentParams,
    DidCloseTextDocumentParams, DidOpenTextDocumentParams, DidSaveTextDocumentParams,
    HoverProviderCapability, InitializeParams, NumberOrString, OneOf, Position,
    PublishDiagnosticsParams, Range, ServerCapabilities, TextDocumentSyncCapability,
    TextDocumentSyncKind, Url,
};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::error::Error;
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use threadpool::ThreadPool;
use walkdir::WalkDir;

use crate::symbols::{document_hover_request, document_symbol_request};

mod symbols;

// `STD_MODULES` — generated by build.rs, identical to yelc2's registry.
include!(concat!(env!("OUT_DIR"), "/std_modules.rs"));

fn main() -> Result<(), Box<dyn Error + Sync + Send>> {
    // Stderr is the log channel — the editor captures it (Zed: `dev: open
    // language server logs`). `env_logger`'s default filter is `error`, which
    // renders the server silent in exactly the situation logs exist for, so
    // default to `info`; `RUST_LOG` still overrides in either direction.
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();

    let (connection, io_threads) = Connection::stdio();
    log::info!(
        "yelc-lsp {} starting (RUST_LOG overrides log level)",
        env!("CARGO_PKG_VERSION")
    );

    let (id, params) = connection.initialize_start()?;

    let init_params: InitializeParams = serde_json::from_value(params).unwrap();
    let client_capabilities: ClientCapabilities = init_params.capabilities;
    let client_workspace_folders = init_params.workspace_folders.unwrap_or_default();
    let mut workspace_folders = Vec::new();

    for workspace_folder in client_workspace_folders {
        let file_path = workspace_folder
            .uri
            .to_file_path()
            .expect("file path expected");
        assert!(file_path.is_absolute());
        log::info!("workspace folder: {}", file_path.display());
        workspace_folders.push(file_path);
    }

    let hover_provider = Some(HoverProviderCapability::Simple(true));

    let server_capabilities = ServerCapabilities {
        text_document_sync: Some(TextDocumentSyncCapability::Kind(TextDocumentSyncKind::FULL)),
        hover_provider,
        document_symbol_provider: Some(OneOf::Left(true)),
        ..Default::default()
    };

    let initialize_data = serde_json::json!({
        "capabilities": server_capabilities,
        "serverInfo": {
            "name": "yelc-lsp",
            "version": env!("CARGO_PKG_VERSION"),
        }
    });

    let projects = find_projects(&workspace_folders);
    log::info!("{} project(s) discovered", projects.len());
    for project in &projects {
        log::info!("project {} -> {}", project.name, project.main.display());
    }

    let hover_config = HoverConfig::from_options(init_params.initialization_options.as_ref());

    connection.initialize_finish(id, initialize_data)?;
    let mut state = ServerState::new(
        client_capabilities,
        workspace_folders,
        projects,
        hover_config,
    );
    event_loop(&mut state, &connection)?;
    io_threads.join()?;
    Ok(())
}

pub(crate) struct ServerState {
    pub(crate) opened_files: HashMap<PathBuf, Arc<str>>,

    #[allow(dead_code)]
    client_capabilities: ClientCapabilities,
    #[allow(dead_code)]
    workspace_folders: Vec<PathBuf>,
    projects: Vec<ProjectConfig>,
    files_with_errors: HashSet<PathBuf>,
    pub(crate) hover_config: HoverConfig,

    pub(crate) threadpool: ThreadPool,
    pub(crate) threadpool_sender: Sender<MainLoopTask>,
    threadpool_receiver: Receiver<MainLoopTask>,
}

impl ServerState {
    fn new(
        client_capabilities: ClientCapabilities,
        workspace_folders: Vec<PathBuf>,
        projects: Vec<ProjectConfig>,
        hover_config: HoverConfig,
    ) -> ServerState {
        let threadpool = ThreadPool::new(6);
        let (sender, receiver) = crossbeam::channel::unbounded();

        ServerState {
            opened_files: HashMap::new(),
            client_capabilities,
            workspace_folders,
            projects,
            files_with_errors: HashSet::new(),
            hover_config,
            threadpool,
            threadpool_sender: sender,
            threadpool_receiver: receiver,
        }
    }
}

/// The two `HoverConfig` fields rust-analyzer's `render::keyword` gates on —
/// `config.documentation` and `config.keywords`, the latter being
/// `rust-analyzer.hover.documentation.keywords.enable`. Same defaults (both
/// on) and the same nesting, under `yel` instead: keyword prose is the kind of
/// thing an experienced user wants to switch off once they have read it, and a
/// hover feature with no off switch is one people disable wholesale.
#[derive(Clone, Copy)]
pub(crate) struct HoverConfig {
    pub(crate) documentation: bool,
    pub(crate) keywords: bool,
}

impl Default for HoverConfig {
    fn default() -> Self {
        HoverConfig {
            documentation: true,
            keywords: true,
        }
    }
}

impl HoverConfig {
    /// Read once from `initializationOptions`, not per request: this server has
    /// no `workspace/didChangeConfiguration` handler, so a value that could
    /// change mid-session would be a setting that silently never takes effect.
    fn from_options(options: Option<&serde_json::Value>) -> HoverConfig {
        let read = |path: &[&str]| -> Option<bool> {
            let mut value = options?;
            for key in path {
                value = value.get(key)?;
            }
            value.as_bool()
        };
        let defaults = HoverConfig::default();
        HoverConfig {
            documentation: read(&["hover", "documentation", "enable"])
                .unwrap_or(defaults.documentation),
            keywords: read(&["hover", "documentation", "keywords", "enable"])
                .unwrap_or(defaults.keywords),
        }
    }
}

fn event_loop(
    state: &mut ServerState,
    connection: &Connection,
) -> Result<(), Box<dyn Error + Sync + Send>> {
    let mut event;

    loop {
        event = next_event(state, connection);
        if event.is_none() {
            return Ok(());
        }

        match event {
            Some(Event::LanguageServer(msg)) => {
                // `shutdown` is protocol, not a feature: `handle_shutdown`
                // sends the empty reply and waits for the paired `exit`.
                // Without this the client's clean teardown times out and it
                // has to kill the process instead.
                if let Message::Request(request) = &msg
                    && connection.handle_shutdown(request)?
                {
                    log::info!("shutdown requested; exiting");
                    return Ok(());
                }
                handle_message(state, msg);
            }
            Some(Event::MainLoopTask(task)) => handle_main_loop_task(state, connection, task),
            None => {
                return Ok(());
            }
        }
    }
}

fn next_event(state: &mut ServerState, connection: &Connection) -> Option<Event> {
    select! {
        recv(connection.receiver) -> msg => {
            match msg {
                Ok(msg) => {
                    if let Message::Notification(ref notification) = msg
                        && notification.method == notification::Exit::METHOD
                    {
                        return None;
                    }

                    Some(Event::LanguageServer(msg))
                }

                Err(error) => {
                    log::error!("error from lsp connection: {error}");
                    None
                }
            }
        }

        recv(state.threadpool_receiver) -> msg => {
            match msg {
                Ok(msg) => Some(Event::MainLoopTask(msg)),
                Err(error) => {
                    log::error!("error from thread pool: {error}");
                    None
                }
            }
        }
    }
}

fn handle_main_loop_task(state: &mut ServerState, connection: &Connection, task: MainLoopTask) {
    match task {
        MainLoopTask::OpenedFile(path, content) => {
            state.opened_files.insert(path, content);
        }
        MainLoopTask::SendResponse(msg) => connection.sender.send(msg).expect("send failed"),
        MainLoopTask::ReportError(errors_by_file) => {
            let mut last_files_with_errors = std::mem::take(&mut state.files_with_errors);

            for (file, errors) in &errors_by_file {
                log::info!(
                    "publish {} diagnostic(s) for {}",
                    errors.len(),
                    file.display()
                );
            }
            for (file, errors) in errors_by_file {
                let params = PublishDiagnosticsParams {
                    uri: Url::from_file_path(&file).expect("broken file path"),
                    version: None,
                    diagnostics: errors,
                };

                let notification =
                    Notification::new("textDocument/publishDiagnostics".into(), params);

                connection
                    .sender
                    .send(Message::Notification(notification))
                    .expect("send() failed");

                last_files_with_errors.remove(&file);
                state.files_with_errors.insert(file);
            }

            // Files that had errors last round and none this round get an
            // explicit empty publish — ark's stale-diagnostics clearing.
            for file in last_files_with_errors {
                let params = PublishDiagnosticsParams {
                    uri: Url::from_file_path(&file).expect("broken file path"),
                    version: None,
                    diagnostics: Vec::new(),
                };

                let notification =
                    Notification::new("textDocument/publishDiagnostics".into(), params);

                connection
                    .sender
                    .send(Message::Notification(notification))
                    .expect("send() failed");
            }
        }
    }
}

fn handle_message(state: &mut ServerState, msg: Message) {
    match msg {
        Message::Notification(notification) => {
            log::debug!("<- notification {}", notification.method);
            if notification.method == notification::DidChangeTextDocument::METHOD {
                did_change_notification(state, notification);
            } else if notification.method == notification::DidOpenTextDocument::METHOD {
                did_open_notification(state, notification);
            } else if notification.method == notification::DidCloseTextDocument::METHOD {
                did_close_notification(state, notification);
            } else if notification.method == notification::DidSaveTextDocument::METHOD {
                did_save_notification(state, notification);
            } else {
                log::debug!("unknown notification {}", notification.method);
            }
        }

        Message::Request(request) => {
            log::debug!("<- request {} (#{})", request.method, request.id);
            if request.method == request::DocumentSymbolRequest::METHOD {
                document_symbol_request(state, request);
            } else if request.method == request::HoverRequest::METHOD {
                document_hover_request(state, request);
            } else if request.method == "$/cancelRequest" {
                // Nothing to cancel: every request recomputes from scratch.
            } else {
                log::info!("unknown request {}", request.method);
            }
        }

        Message::Response(response) => log::info!("unknown response {:?}", response.result),
    }
}

/// One compile of the package containing `path`, with every open buffer
/// overlaid, reported per file — ark's `compile_project` with yel's frontend.
pub(crate) fn compile_package(
    sender: Sender<MainLoopTask>,
    package_root: PathBuf,
    overlays: Vec<(PathBuf, Arc<str>)>,
) {
    let mut context = yelc_sema::CompilerContext::with_intrinsics(yelc_sema::PackageId::LOCAL);
    // The single-overlay frontend entry; the editing file is what changed.
    let overlay = overlays
        .iter()
        .find(|(path, _)| path.parent() == Some(&package_root))
        .map(|(path, content)| (path.as_path(), &**content));
    let result = yelc_hir::check_package_with_overlay(
        &package_root,
        overlay,
        &[],
        STD_MODULES,
        &mut context,
    );

    let mut errors_by_file: HashMap<PathBuf, Vec<Diagnostic>> = HashMap::new();
    match result {
        Ok(_) => {
            for diagnostic in context.diagnostics.iter() {
                let Some(span) = diagnostic.span else {
                    continue;
                };
                let Some(source) = context.sources.get(span.source) else {
                    continue;
                };
                let start = position_from_source(source, span.start);
                let end = position_from_source(source, span.end);
                errors_by_file
                    .entry(PathBuf::from(source.name()))
                    .or_default()
                    .push(Diagnostic {
                        range: Range::new(start, end),
                        severity: Some(match diagnostic.severity {
                            yelc_base::Severity::Error => DiagnosticSeverity::ERROR,
                            yelc_base::Severity::Warning => DiagnosticSeverity::WARNING,
                            yelc_base::Severity::Note => DiagnosticSeverity::INFORMATION,
                        }),
                        code: diagnostic
                            .code
                            .map(|code| NumberOrString::String(code.code().to_string())),
                        message: match diagnostic.notes.as_slice() {
                            [] => diagnostic.message.clone(),
                            notes => format!("{}\n{}", diagnostic.message, notes.join("\n")),
                        },
                        ..Default::default()
                    });
            }
        }
        Err(message) => log::error!("cannot compile {}: {message}", package_root.display()),
    }

    sender
        .send(MainLoopTask::ReportError(errors_by_file))
        .expect("failed send");
}

/// Ark parses the single file here; yel compiles the whole package the file
/// belongs to, because packageck and includes are package-level and a
/// single-file parse would hide their diagnostics.
fn analyze_file(state: &mut ServerState, path: PathBuf, content: Arc<str>) {
    let sender = state.threadpool_sender.clone();
    sender
        .send(MainLoopTask::OpenedFile(path.clone(), content.clone()))
        .expect("send failed");

    let Some(package_root) = path.parent().map(Path::to_path_buf) else {
        return;
    };
    let overlays: Vec<(PathBuf, Arc<str>)> = std::iter::once((path, content)).collect();
    let sender = state.threadpool_sender.clone();
    state.threadpool.execute(move || {
        compile_package(sender, package_root, overlays);
    });
}

fn did_change_notification(state: &mut ServerState, notification: Notification) {
    let result = serde_json::from_value::<DidChangeTextDocumentParams>(notification.params);

    match result {
        Ok(result) => {
            let path = result
                .text_document
                .uri
                .to_file_path()
                .expect("file path expected");
            let content: Arc<str> = Arc::from(result.content_changes[0].text.as_str());
            analyze_file(state, path, content);
        }

        Err(_) => {
            log::error!("malformed notification params");
        }
    }
}

fn did_open_notification(state: &mut ServerState, notification: Notification) {
    let result = serde_json::from_value::<DidOpenTextDocumentParams>(notification.params);
    if let Ok(result) = result {
        let path = result
            .text_document
            .uri
            .to_file_path()
            .expect("file path expected");
        let content: Arc<str> = Arc::from(result.text_document.text);
        analyze_file(state, path, content);
    }
}

fn did_close_notification(state: &mut ServerState, notification: Notification) {
    let result = serde_json::from_value::<DidCloseTextDocumentParams>(notification.params);
    if let Ok(result) = result {
        let path = result
            .text_document
            .uri
            .to_file_path()
            .expect("file path expected");
        state.opened_files.remove(&path);
    }
}

fn did_save_notification(state: &mut ServerState, notification: Notification) {
    let result = serde_json::from_value::<DidSaveTextDocumentParams>(notification.params);

    if result.is_ok() {
        let sender = state.threadpool_sender.clone();
        let projects = state.projects.clone();

        state.threadpool.execute(move || {
            for project in projects {
                compile_package(sender.clone(), project.main.clone(), Vec::new());
            }
        })
    }
}

/// Byte offset → LSP position through the compiled `Source` (1-based
/// line/col, converted like ark's `compute_line_column` call sites).
pub(crate) fn position_from_source(source: &yelc_base::Source, offset: usize) -> Position {
    let (line, column) = source.line_col(offset);
    Position::new(line as u32 - 1, column as u32 - 1)
}

/// Ark walks for `ark-project.json`; yel's package is a **directory**, so a
/// `yel-project.json` is honored when present and otherwise any directory
/// directly containing `.yel` files is a project.
fn find_projects(workspaces: &[PathBuf]) -> Vec<ProjectConfig> {
    let mut projects = Vec::new();
    let mut seen = HashSet::new();

    for workspace in workspaces {
        for entry in WalkDir::new(workspace) {
            let Ok(entry) = entry else { continue };
            if entry.file_name() == "yel-project.json" {
                match read_project_json(entry.path()) {
                    Ok(config) => {
                        let path = entry.path().parent().expect("no parents");
                        let main = path.join(&config.main);
                        if seen.insert(main.clone()) {
                            projects.push(ProjectConfig {
                                name: config.name,
                                main,
                            });
                        }
                    }
                    Err(_) => {
                        log::warn!("invalid project config at {}", entry.path().display());
                    }
                }
            } else if entry
                .path()
                .extension()
                .is_some_and(|extension| extension == "yel")
            {
                let Some(directory) = entry.path().parent() else {
                    continue;
                };
                if seen.insert(directory.to_path_buf()) {
                    projects.push(ProjectConfig {
                        name: directory
                            .file_name()
                            .map(|name| name.to_string_lossy().into_owned())
                            .unwrap_or_else(|| "package".into()),
                        main: directory.to_path_buf(),
                    });
                }
            }
        }
    }

    projects
}

fn read_project_json(path: &Path) -> Result<ProjectJsonConfig, Box<dyn Error>> {
    let mut file = File::open(path)?;
    let mut content = String::new();
    file.read_to_string(&mut content)?;

    let value: serde_json::Value = serde_json::from_str(&content)?;
    let parsed_value = serde_json::from_value::<ProjectJsonConfig>(value)?;

    Ok(parsed_value)
}

pub(crate) enum MainLoopTask {
    OpenedFile(PathBuf, Arc<str>),
    SendResponse(Message),
    ReportError(HashMap<PathBuf, Vec<Diagnostic>>),
}

enum Event {
    LanguageServer(Message),
    MainLoopTask(MainLoopTask),
}

#[derive(Clone)]
struct ProjectConfig {
    name: String,
    /// The package directory (ark: the main *file*; yel packages are
    /// directories).
    main: PathBuf,
}

#[derive(Serialize, Deserialize)]
struct ProjectJsonConfig {
    name: String,
    main: String,
    #[serde(default)]
    packages: Vec<String>,
}
