// Generate bindings using wit-bindgen macro
// Following the same pattern as yelc/src/lib.rs
wit_bindgen::generate!({
    world: "counter-logic",
    path: "wit/counter-callbacks.wit",
});

use exports::yel::counter::counter_callbacks::Guest;

/// Business logic implementation for the counter component
struct CounterLogic;

impl Guest for CounterLogic {
    fn test() {
        // Business logic implementation
        // This would typically interact with state, database, etc.
        // For now, we just log that increment was called
        // In a real implementation, this might update shared state,
        // trigger side effects, or call other services
        println!("Increment callback called from UI component");
    }
}

// Export the CounterLogic type to make it available as a WASM component
// The export! macro is generated by wit_bindgen::generate!
export!(CounterLogic);
