//! `yelc2` — the rewrite's driver.
//!
//! Ark's shape, taken all the way (`arkc/src/main.rs` →
//! `arkc_frontend::check_program` + frontend-side emitters): this binary
//! parses flags, converts them to the frontend's clap-free
//! [`yelc_hir::RunArgs`], supplies the embedded stdlib bytes its `build.rs`
//! produced, and exits with what `yelc_hir::run` returns. There is nothing
//! else here, on purpose — a driver that decides anything becomes a third
//! implementation to keep in sync with two others.

use std::path::PathBuf;

use clap::Parser;

// `STD_MODULES: &[(&str, &[u8])]` — generated by build.rs, one entry per
// `stdlib/<name>.yel`. The driver owns the *bytes* (binary packaging); what
// they mean is the frontend's business, which takes them as a parameter —
// ark's `SemaArgs.packages` shape.
include!(concat!(env!("OUT_DIR"), "/std_modules.rs"));

#[derive(Parser)]
#[command(name = "yelc2")]
#[command(about = "Yel compiler (rewrite) — parse a file and emit its IRs", long_about = None)]
pub struct Args {
    /// The package to compile: a **directory** of `.yel` files.
    ///
    /// A single file is also accepted and read as a one-file package, which
    /// keeps `--emit-green-text` — a per-file instrument — usable.
    pub path: PathBuf,

    /// Emit the typed AST. Optionally filter to one top-level item by name,
    /// written `--emit-ast=Counter`.
    ///
    /// `require_equals` is load-bearing, not style. With an optional value and
    /// no `=`, clap reads the **next token** as the filter — so
    /// `--emit-ast counter/` filtered for an item named `counter/` and then
    /// reported the package argument missing. The separator makes the value
    /// unambiguous and gives the positional back.
    #[arg(long, value_name = "ITEM", num_args = 0..=1, require_equals = true, default_missing_value = "")]
    pub emit_ast: Option<String>,

    /// Emit the green tree — kinds and widths, trivia included.
    #[arg(long)]
    pub emit_green: bool,

    /// Emit the HIR: the definition table with resolved declared types, and
    /// every item desugared and name-resolved. Yel-flavoured, deliberately not
    /// round-trippable — `--emit-green-text` is the round-trip instrument.
    #[arg(long)]
    pub emit_hir: bool,

    /// Emit the builtin table and the resolved lang-items.
    ///
    /// Depends on no source input, which is what makes it comparable against
    /// the frozen compiler's tables *before* a file is parsed — the standalone
    /// checkpoint `yelc-sema::stdlib` owes.
    #[arg(long)]
    pub emit_intrinsics: bool,

    /// Emit `green.text()`: the source reconstructed from the tree.
    ///
    /// Invariant S1 says this equals the input byte for byte, for every input,
    /// including one that does not parse. This is how you look at it.
    #[arg(long)]
    pub emit_green_text: bool,

    /// Include `NodeId` on every AST node.
    ///
    /// Taken from rustc's `-Z unpretty=…,identified`. The capability is worth
    /// having — a diagnostic or an LSP request has to be pointed at a node. The
    /// flag name is not: rustc's `--unpretty` is named against a `--pretty`
    /// that was removed years ago.
    #[arg(long)]
    pub identified: bool,

    /// Include byte spans on every AST node.
    #[arg(long)]
    pub spans: bool,

    /// Dump the AST as the raw `Debug` structure, one file at a time.
    ///
    /// The `--debug-*` family prints structures exactly as the compiler holds
    /// them — `{:#?}`, every field, no curation. The price of raw: hash-map
    /// fields print in hash order, so the output is **not byte-stable across
    /// runs** and must never become a golden. The `--emit-*` family is the
    /// curated, stable view; this family is for looking at what is actually
    /// there.
    #[arg(long)]
    pub debug_ast: bool,

    /// Dump the symbol table (`Definitions`) — and every imported package's —
    /// as the raw `Debug` structure. Same caveats as `--debug-ast`.
    #[arg(long)]
    pub debug_defs: bool,

    /// Dump the HIR (`HirModule`: items, bodies, map, dependency tables) as
    /// the raw `Debug` structure. Same caveats as `--debug-ast`.
    #[arg(long)]
    pub debug_hir: bool,

    /// A directory to search for included modules (`from "list" include
    /// List;` looks for `list.yelmod`). Repeatable; searched in the order
    /// given. `std:` specifiers are never searched here — that prefix names
    /// modules the compiler itself will ship.
    #[arg(long = "include", value_name = "DIR")]
    pub include_directories: Vec<PathBuf>,

    /// Write the package's serialized module — its typed declaration surface —
    /// to PATH. Signatures and member rows, no bodies; the format is
    /// `yelc-sema`'s postcard artifact, stamped with compiler + format
    /// version. Refused when the compilation has errors: an artifact from a
    /// failed build is a corrupt cache, not a partial one.
    #[arg(long, value_name = "PATH")]
    pub emit_module: Option<PathBuf>,
}

impl Args {
    /// The clap surface, converted to the frontend's plain args.
    fn into_run_args(self) -> yelc_hir::RunArgs {
        yelc_hir::RunArgs {
            path: self.path,
            include_directories: self.include_directories,
            emit_ast: self.emit_ast,
            emit_green: self.emit_green,
            emit_green_text: self.emit_green_text,
            emit_intrinsics: self.emit_intrinsics,
            emit_hir: self.emit_hir,
            emit_module: self.emit_module,
            identified: self.identified,
            spans: self.spans,
            debug_ast: self.debug_ast,
            debug_defs: self.debug_defs,
            debug_hir: self.debug_hir,
        }
    }
}

fn main() {
    std::process::exit(yelc_hir::run(&Args::parse().into_run_args(), STD_MODULES));
}
