//! Compile the stdlib to module artifacts at build time and hand the driver
//! the bytes.
//!
//! The compiler compiles its own stdlib: each `stdlib/<name>.yel` at the
//! workspace root becomes `<name>.yelmod` in `OUT_DIR` through the same
//! pipeline a user package takes — parse, package check, lower, refuse on
//! errors — and a generated `std_modules.rs` maps `std:<name>` to the embedded
//! bytes. `Stamp::current()` here and in the driver come from the same
//! `yelc-sema` build, so the embedded artifacts always pass their own stamp
//! check.
//!
//! # A stdlib error fails the build, loudly
//!
//! No skipping, no partial set: a stdlib file that stops compiling is a
//! compiler regression the moment it happens, and a build that quietly ships
//! without `std:num` turns that regression into a user-facing "module not
//! found" with no trail back. The panic below prints the rendered diagnostics.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use yelc_sema::{Artifact, CompilerContext, PackageId, PackageName, artifact};
use yelc_syntax::ParsedFile;

fn main() {
    let stdlib = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../stdlib");
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    println!("cargo::rerun-if-changed={}", stdlib.display());

    let mut sources: Vec<PathBuf> = std::fs::read_dir(&stdlib)
        .expect("stdlib directory readable")
        .filter_map(|entry| {
            let path = entry.expect("stdlib entry").path();
            (path.extension().is_some_and(|extension| extension == "yel")).then_some(path)
        })
        .collect();
    sources.sort();
    assert!(
        !sources.is_empty(),
        "no .yel files in {} — the stdlib is missing",
        stdlib.display()
    );

    let mut registry = String::from(
        "/// Generated by build.rs — the embedded stdlib, one module per\n\
         /// `stdlib/<name>.yel`, resolvable as `std:<name>`.\n\
         pub static STD_MODULES: &[(&str, &[u8])] = &[\n",
    );
    for source in &sources {
        let name = source
            .file_stem()
            .expect("stdlib file has a stem")
            .to_string_lossy()
            .to_string();
        let bytes = compile(source);
        let module = out.join(format!("{name}.yelmod"));
        std::fs::write(&module, &bytes).expect("write module to OUT_DIR");
        let _ = writeln!(
            registry,
            "    ({name:?}, include_bytes!({:?})),",
            module.display()
        );
    }
    registry.push_str("];\n");
    std::fs::write(out.join("std_modules.rs"), registry).expect("write registry");
}

/// One stdlib file through the real pipeline. Each file is its own single-file
/// package (they all declare `yel:std`, which is fine — packages are compiled
/// independently and the module name comes from the file, not the clause).
fn compile(source: &Path) -> Vec<u8> {
    let content = std::fs::read_to_string(source).expect("stdlib file readable");
    let mut context = CompilerContext::with_intrinsics(PackageId::LOCAL);
    let id = context.sources.add_file(source, content.clone());
    let parsed: Vec<ParsedFile> = vec![yelc_syntax::parse(
        id,
        &content,
        &context.names,
        &mut context.diagnostics,
    )];
    let identity = yelc_hir::check_package_identity(&parsed, &mut context);
    let _ = yelc_hir::lower_files(&parsed, &mut context);

    if context.diagnostics.has_errors() {
        panic!(
            "stdlib file {} does not compile:\n{}",
            source.display(),
            context.diagnostics.render(&context.sources),
        );
    }
    let identity = identity.expect("a clean stdlib file declared its package");
    let package = PackageName::new(
        context.names.str(identity.namespace).to_string(),
        context.names.str(identity.name).to_string(),
        identity
            .version
            .map(|version| context.names.str(version).to_string())
            .unwrap_or_default(),
    );
    artifact::encode(&Artifact::from_context(package, &context))
}
